global using Catalog.API.Data;
global using Catalog.API.Endpoints;
global using Catalog.API.Models;
global using Catalog.API.Services;
global using MassTransit;
global using Microsoft.EntityFrameworkCore;
global using ServiceDefaults.Messaging;
global using ServiceDefaults.Messaging.Events;
global using System.Reflection;
